services:
  twochi-verifier-be:
    build:
      target: test
    command: ["gleam", "run"]
    container_name: twochi-verifier-be
    stop_signal: sigkill
    ports:
      - 8000:8000
    depends_on:
      - bot-api
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: .

  mongodb:
    image: mongo:bionic
    container_name: mongodb-2chi-verifier-be
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bot
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  bot-api:
    image: ghcr.io/siesta-cat/2chi-api:v1.2.7
    container_name: 2chi-api-2chi-verifier-be
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      PORT: 8080
      DB_HOST: "mongodb"
      DB_NAME: "bot"
      DB_USER: "root"
      DB_PASS: "password"
