name: test
permissions:
  contents: read

on:
  push:
    branches:
      - master
      - main
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: gleam format --check src test
      - run: docker compose run --build twochi-verifier-be gleam test
